### ISSUE TITLE
Not working in Mac OSX 10.11.1

### ISSUE THREAD

**Issue by anggamaulana** [niklauslee/staruml-ddl#1]
I tried to find log file in package apps folder and run it from terminal, but there's no error displayed. it can't generate the file. Other extensions such as code generator work fine, so there's nothing wrong in file permission i guess.

**Comment by niklauslee** [comment]
It works fine in Mac OS X 10.11.4. Please check the errors (Debug > Show DevTools). It creates a .ddl file, not a directory that other generators create.

**Comment by anggamaulana** [comment]
![screen shot 2016-05-06 at 12 51 20 pm](https://cloud.githubusercontent.com/assets/3243163/15065383/4b5f5be8-1389-11e6-9920-a6e0092ac306.png)

I just made simple test, or maybe i'm wrong when making diagram.  is there any rules i should follow to make it work?

**Comment by niklauslee** [comment]
Thank you for your feedback! The error occurred because there is no PK (Primary Key). Anyway, this case should be handled by this extension. So this problem has fixed and now it's available in Extension Registry (v0.9.1)
